language: scala

scala:
  2.11.8

jdk:
  - oraclejdk8

script:
  - sbt clean coverage test coverageReport

after_success:
- bash <(curl -s https://codecov.io/bash) -t 0d507bfb-ebca-4588-991b-a64d84fd4014
